name: website

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  charts_common:
dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

flutter:
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: fonts/HelveticaNeueBold.otf
        - asset: fonts/HelveticaNeueMediumItalic.otf
          style: italic
  uses-material-design: true